on:
  push:
    branches:
      - main

name: algolia-search
jobs:
  algolia-search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
      
      - name: Generate changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.3
          
      - name: Install dependencies and push records
        run: |
          cd ./docs/
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec jekyll algolia
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
